export type SeoContentBlock = {
  title: string;
  body: string;
};

export type PageSeoContent = {
  heading: string;
  introduction: string;
  blocks: SeoContentBlock[];
};

const locationHeroTitles: Record<string, string> = {
  "mont-fleuri": "Traditional Safas in Mont Fleuri",
  "bel-air": "Destination Safas in Bel Air",
  "english-river": "Designer Safas in English River",
  "saint-louis": "Baraati Safas in Saint Louis",
  "roche-caiman": "Groom Pagdis in Roche Caiman",
  "beau-vallon": "Destination Safas in Beau Vallon",
  "anse-royale": "Traditional Safas in Anse Royale",
  "anse-boileau": "Wedding Pagdis in Anse Boileau",
  "grand-anse": "Designer Safas in Grand Anse",
  "glacis": "Designer Safas in Glacis",
  "bel-ombre": "Groom Pagdis in Bel Ombre",
  "takamaka": "Elegant Safas in Takamaka",
  "baie-lazare": "Traditional Safas in Baie Lazare",
  "port-glaud": "Elegant Safas in Port Glaud",
  "baie-sainte-anne": "Elegant Safas in Baie Sainte Anne",
  "anse-volbert": "Wedding Pagdis in Anse Volbert",
  "grand-anse-praslin": "Wedding Pagdis in Grand Anse Praslin",
  "la-passe": "Royal Safas in La Passe",
  "la-reunion": "Traditional Safas in La Reunion",
  "anse-source-d-argent": "Groom Pagdis in Anse Source d'Argent",
};

const serviceHeroTitles: Record<string, string> = {
  "wedding-safa-tying": "Professional Wedding Safa Tying",
  "groom-pagdi": "Signature Groom Pagdi Styling",
  "baraati-safa": "Coordinated Baraati Safas",
  "destination-wedding-safa": "Destination Wedding Safa Team",
  "family-pagdi": "Refined Family Pagdi Styling",
  "custom-safa-colours": "Custom Wedding Safa Colours",
};

export function getHeroTitle(slug: string, kind: "location" | "service") {
  const title = kind === "location" ? locationHeroTitles[slug] : serviceHeroTitles[slug];
  if (!title) throw new Error(`Missing hero title for ${kind}: ${slug}`);
  return title;
}

const locationProfiles: Record<string, [string, string, string]> = {
  "mont-fleuri": [
    "Mont Fleuri is a practical base for families whose ceremonies and accommodation sit on different sides of the Seychelles service area. Our wedding safa wala in Mont Fleuri plans the groom pagdi first, followed by close relatives and the wider wedding party.",
    "Traditional wedding pagdis in maroon, saffron, cream or muted gold suit both temple-led ceremonies and hotel celebrations here. Parents and brothers can use a coordinated family pagdi while the groom keeps a more detailed kalgi or brooch finish, and this pagdi tying in Mont Fleuri stays organised around one shared preparation room.",
    "Because meeting points can cause avoidable delays, the booking should carry the exact entrance, preparation floor and coordinator number. A confirmed headcount helps us divide professional pagdi tying in Mont Fleuri into fast, orderly batches.",
  ],
  "bel-air": [
    "Bel Air is well suited to both home-based and venue-based wedding preparation, and a wedding safa wala in Bel Air can move between the two without losing time if the schedule is confirmed early.",
    "Rich reds, warm golds and classic maroon safas remain popular for Bel Air ceremonies, while couples choosing a more modern reception often prefer ivory or pastel groom pagdi styling instead. Both directions are planned by the same Bel Air tying team.",
    "A complete Bel Air safa booking separates the groom's detailed session from the faster family and baraati tying. This is the most reliable way to keep a Bel Air wedding safa appointment on schedule from morning through departure.",
  ],
  "english-river": [
    "A wedding safa wala in English River typically works with families who want the groom styled well before guests begin arriving, so the English River session is planned as the very first booking of the day.",
    "Classic Rajwadi and Jodhpuri profiles suit English River's mix of traditional and contemporary venues, and either can be finished in ivory, maroon or antique gold depending on the sherwani. The rest of the English River wedding party then follows in coordinated but simpler safas.",
    "For English River bookings, share whether the ceremony and reception happen at the same address or two different ones. This single detail changes how the English River safa tying team plans travel between the groom's session and the baraati batches.",
  ],
  "saint-louis": [
    "A wedding safa wala in Saint Louis typically works with families who want the groom styled well before guests begin arriving, so the Saint Louis session is planned as the very first booking of the day.",
    "Classic Rajwadi and Jodhpuri profiles suit Saint Louis's mix of traditional and contemporary venues, and either can be finished in ivory, maroon or antique gold depending on the sherwani. The rest of the Saint Louis wedding party then follows in coordinated but simpler safas.",
    "For Saint Louis bookings, share whether the ceremony and reception happen at the same address or two different ones. This single detail changes how the Saint Louis safa tying team plans travel between the groom's session and the baraati batches.",
  ],
  "roche-caiman": [
    "Roche Caiman hosts a mix of compact family functions and larger multi-day celebrations, so a wedding safa service in Roche Caiman is quoted after the guest count and number of functions are known, not before.",
    "Groom pagdi styling in Roche Caiman is treated as its own appointment, separate from the quicker baraati safa tying that follows. This keeps the Roche Caiman groom's look distinct in every wedding photograph.",
    "When booking a safa wala for Roche Caiman, include the reporting time for each separate function if there is more than one. This is the detail that most affects how many artists a Roche Caiman wedding safa booking actually needs.",
  ],
  "beau-vallon": [
    "Beau Vallon is treated as a planned outstation booking rather than a same-city appointment, which means the wedding safa wala confirms travel time to Beau Vallon before agreeing on a reporting slot.",
    "A structured groom pagdi in ivory or rust suits Beau Vallon's typical venue style, and family members can be styled in a lighter matching fold once the groom's session is finished.",
    "The most useful Beau Vallon booking includes the venue pin, ready-by time and total safa quantity in one message, so the team can confirm availability for Beau Vallon without back-and-forth questions.",
  ],
  "anse-royale": [
    "Anse Royale weddings range from lawns to hotel and resort celebrations, so the wedding safa service in Anse Royale must be built around the property rather than a generic city schedule. We coordinate the groom's private session with the wider Anse Royale wedding-party flow.",
    "Designer groom pagdis in ivory, sage, wine or muted gold suit Anse Royale's modern venue style, while Bandhani or maroon baraati safas bring stronger traditional colour. Fabric for the Anse Royale booking is reviewed for both daylight portraits and indoor lighting.",
    "For a Anse Royale wedding safa package, share venue access, guest quantity and whether the same team is required for more than one function. Travel time to Anse Royale and an early start may require an additional artist or previous-day setup.",
  ],
  "anse-boileau": [
    "Anse Boileau weddings can be covered by an advance-scheduled safa team for complete family and baraati groups. A single coordinator keeps Anse Boileau guests moving through the tying area while the groom receives a separate detailed appointment.",
    "Deep red, wine, mustard and cream traditional safas suit large Anse Boileau celebrations and evening venue lighting. For close family, a bordered pagdi or brooch detail can create hierarchy without introducing unrelated colours into the Anse Boileau wedding party.",
    "An early reporting time is often the safest choice for outstation wedding turban tying in Anse Boileau. Confirm headcount, venue access and procession time so the artists and fabric reach the Anse Boileau property with a sensible buffer.",
  ],
  "grand-anse": [
    "Grand Anse is popular for weddings that want a change of scenery without a very long journey, so the wedding safa wala plans Grand Anse bookings as a single-day travel assignment where possible.",
    "Ivory, rust and muted gold groom pagdis photograph well in Grand Anse's outdoor settings, while the baraat typically uses a simpler, faster fold in a complementary colour to keep the Grand Anse group looking coordinated.",
    "Confirm the Grand Anse venue access and reporting time well ahead of the date, since same-day changes are harder to accommodate once the team has already travelled to Grand Anse.",
  ],
  "glacis": [
    "Couples choosing Glacis for a wedding usually do so for the setting rather than convenience, so the travelling wedding safa team treats Glacis as a full destination assignment with its own travel and setup plan.",
    "A groom pagdi built for Glacis needs to hold its shape through longer outdoor portrait sessions, so structured Rajwadi and Jodhpuri folds are the most common choice here. Family safas for the same Glacis function stay lighter and quicker to tie.",
    "Because Glacis sits outside the home city, confirm accommodation for the artists alongside the venue pin and reporting time. This is the detail most Glacis bookings miss until the week of the wedding.",
  ],
  "bel-ombre": [
    "Bel Ombre functions are usually planned well in advance, so the wedding safa wala treats every Bel Ombre booking as a scheduled assignment rather than a same-week enquiry.",
    "Warm reds, maroon and antique gold remain the most requested palette for Bel Ombre ceremonies, giving the groom pagdi a traditional finish that suits both indoor rituals and outdoor procession photographs in Bel Ombre.",
    "A Bel Ombre quote depends on travel distance, guest quantity and whether the team needs to stay overnight. Sharing all three together is the fastest way to get an accurate Bel Ombre wedding safa price.",
  ],
  "takamaka": [
    "Takamaka weddings often bring together guests travelling from more than one city, so the safa tying schedule for Takamaka is built around the slowest arrival, not the fastest.",
    "A groom pagdi for an Takamaka wedding is typically finished first, giving enough time for portraits before the wider baraat is styled. This keeps the Takamaka tying sequence realistic even when some guests are still arriving.",
    "Book the Takamaka wedding safa team with the venue pin, expected arrival window and total headcount in one enquiry. This lets us plan artist numbers for Takamaka without guessing at the final group size.",
  ],
  "baie-lazare": [
    "Baie Lazare bookings are handled as scheduled outstation assignments with a clear arrival and completion window. The wedding safa wala for Baie Lazare brings the approved groom pagdi, family fabrics and guest quantities together rather than depending on local last-minute replacements.",
    "Traditional maroon, rust, cream and red safas work well for large family weddings in Baie Lazare. A refined Jodhpuri or Rajwadi groom profile can add distinction while the Baie Lazare baraat uses a consistent quicker fold.",
    "Finalise quantities and colours before the team departs from Seychelles for Baie Lazare. A complete Baie Lazare booking should include route, venue pin, ready-by time and whether travel or accommodation is needed for an early ceremony.",
  ],
  "port-glaud": [
    "Port Glaud destination weddings are usually hotel-led and strongly focused on photography. The wedding safa service for Port Glaud is planned with resort access, travel and a covered preparation space in mind.",
    "Ivory, muted gold, sage, rust and pastel groom pagdis complement hotel interiors and Port Glaud destination-venue portraits. A softer destination fold or refined Jodhpuri profile keeps the Port Glaud look elegant without feeling oversized in close portraits.",
    "Weather and road timing can affect a Port Glaud booking, especially for morning functions. Confirm whether the artists need accommodation in Port Glaud and keep all approved fabrics at the venue before the wedding-day schedule begins.",
  ],
  "baie-sainte-anne": [
    "Baie Sainte Anne functions can include more than one ceremony across a short trip, so the travelling safa team prepares a schedule covering every Baie Sainte Anne event rather than quoting one appointment at a time.",
    "Deep maroon, saffron and cream remain dependable choices for Baie Sainte Anne ceremonies, and the groom's pagdi is usually finished with one distinguishing accessory so it stays clearly separate from the wider Baie Sainte Anne baraat.",
    "Share every Baie Sainte Anne function date together when requesting a quote, since a multi-day Baie Sainte Anne booking is priced differently from a single standalone wedding safa appointment.",
  ],
  "anse-volbert": [
    "Anse Volbert functions can include more than one ceremony across a short trip, so the travelling safa team prepares a schedule covering every Anse Volbert event rather than quoting one appointment at a time.",
    "Deep maroon, saffron and cream remain dependable choices for Anse Volbert ceremonies, and the groom's pagdi is usually finished with one distinguishing accessory so it stays clearly separate from the wider Anse Volbert baraat.",
    "Share every Anse Volbert function date together when requesting a quote, since a multi-day Anse Volbert booking is priced differently from a single standalone wedding safa appointment.",
  ],
  "grand-anse-praslin": [
    "Couples choosing Grand Anse Praslin for a wedding usually do so for the setting rather than convenience, so the travelling wedding safa team treats Grand Anse Praslin as a full destination assignment with its own travel and setup plan.",
    "A groom pagdi built for Grand Anse Praslin needs to hold its shape through longer outdoor portrait sessions, so structured Rajwadi and Jodhpuri folds are the most common choice here. Family safas for the same Grand Anse Praslin function stay lighter and quicker to tie.",
    "Because Grand Anse Praslin sits outside the home city, confirm accommodation for the artists alongside the venue pin and reporting time. This is the detail most Grand Anse Praslin bookings miss until the week of the wedding.",
  ],
  "la-passe": [
    "La Passe is treated as a planned outstation booking rather than a same-city appointment, which means the wedding safa wala confirms travel time to La Passe before agreeing on a reporting slot.",
    "A structured groom pagdi in ivory or rust suits La Passe's typical venue style, and family members can be styled in a lighter matching fold once the groom's session is finished.",
    "The most useful La Passe booking includes the venue pin, ready-by time and total safa quantity in one message, so the team can confirm availability for La Passe without back-and-forth questions.",
  ],
  "la-reunion": [
    "Couples choosing La Reunion for a wedding usually do so for the setting rather than convenience, so the travelling wedding safa team treats La Reunion as a full destination assignment with its own travel and setup plan.",
    "A groom pagdi built for La Reunion needs to hold its shape through longer outdoor portrait sessions, so structured Rajwadi and Jodhpuri folds are the most common choice here. Family safas for the same La Reunion function stay lighter and quicker to tie.",
    "Because La Reunion sits outside the home city, confirm accommodation for the artists alongside the venue pin and reporting time. This is the detail most La Reunion bookings miss until the week of the wedding.",
  ],
  "anse-source-d-argent": [
    "Anse Source d'Argent weddings can be covered by an advance-scheduled safa team for complete family and baraati groups. A single coordinator keeps Anse Source d'Argent guests moving through the tying area while the groom receives a separate detailed appointment.",
    "Deep red, wine, mustard and cream traditional safas suit large Anse Source d'Argent celebrations and evening venue lighting. For close family, a bordered pagdi or brooch detail can create hierarchy without introducing unrelated colours into the Anse Source d'Argent wedding party.",
    "An early reporting time is often the safest choice for outstation wedding turban tying in Anse Source d'Argent. Confirm headcount, venue access and procession time so the artists and fabric reach the Anse Source d'Argent property with a sensible buffer.",
  ],
};
const locationExtraBlocks: Record<string, [string, string]> = {
  "mont-fleuri": [
    "Mont Fleuri sees weddings across a mix of settings — banquet halls, hotel lawns, rooftop venues and home courtyards — and each one changes how the tying schedule is planned. A hotel booking usually means a fixed preparation room and predictable access, while a home or courtyard function often needs the team to adapt around family rituals happening in parallel. We ask about the venue type early so the right number of artists and the right pace are set from the start, rather than guessing on the day. Peak wedding months in and around Mont Fleuri bring tighter artist availability, so dates during the busiest weeks benefit from earlier confirmation. Off-season and weekday bookings tend to have more flexibility on timing and can sometimes accommodate later confirmations. Either way, the core planning stays the same: confirm the property, the room being used for styling, and roughly how many people need to be ready before the first ritual or the baraat departure. Weather is a smaller factor for most Mont Fleuri bookings since safa tying happens indoors or under cover, but for any outdoor portrait session immediately after styling, we factor in extra time so fabric and finishing hold up under natural light.",
    "Picking the right package for a Mont Fleuri wedding usually comes down to three numbers: how many people need a safa, how much time is available before the ceremony, and how detailed the groom's own styling needs to be. A groom-only booking is the simplest option and works well for smaller functions or when family members already have their own arrangements. A groom-plus-family package adds a coordinated look for parents and siblings without the scale of a full baraati booking. The complete package — groom, family and baraat — is the most common choice for larger Mont Fleuri weddings, since it keeps the whole wedding party visually consistent in photographs and keeps the tying schedule managed by one team rather than several. Fabric quality is a separate decision from group size: some families choose a premium fabric for the groom and a simpler, more economical option for the wider baraat, which keeps costs sensible without compromising the groom's look. Whichever package you're considering, sharing your rough budget alongside the guest count helps us recommend something realistic rather than the largest available option by default. We're happy to talk through two or three package options before you decide.",
  ],
  "bel-air": [
    "Across Bel Air, wedding venues range from compact family halls to larger destination-style properties, and the safa tying plan changes with the scale of the venue. Smaller, more intimate functions usually need a shorter, tighter schedule with the groom styled first and the rest of the group following quickly after. Larger multi-hall or multi-day venues need a longer plan, sometimes spanning more than one function in the same property, and we treat each function as its own booking within the same visit. Local venues in Bel Air are generally easy to access, which keeps setup time short, but properties further from the main area may need an earlier arrival buffer. We recommend sharing the venue name and rough guest count as early as possible, even before the date is fully locked, so we can flag any availability concerns during peak wedding weeks. If the celebration includes more than one ceremony — a haldi, a sangeet, the main wedding — let us know all the dates together so the Bel Air team can plan artist availability across the full run rather than one date at a time.",
    "For Bel Air weddings, the package decision is really a headcount decision first and a style decision second. Once we know how many people need styling — the groom, close family, and the wider baraat if applicable — we can recommend artist numbers and a realistic tying window. Families sometimes assume a bigger package is always safer, but an accurately sized package based on your actual guest list is usually more cost-effective and easier to schedule than an oversized one. If you're unsure of the final numbers this early, a rough range is enough to start the conversation; we'll confirm the exact count closer to the date. Multi-function weddings in Bel Air — where the same family books a haldi, sangeet and wedding day styling — often benefit from a combined package rather than three separate bookings, since it keeps pricing and artist scheduling consistent across all three events. If your celebration includes destination elements, such as a portion of the wedding happening outside Bel Air itself, mention that upfront too, since it changes how the package and travel logistics are structured.",
  ],
  "english-river": [
    "English River sees weddings across a mix of settings — banquet halls, hotel lawns, rooftop venues and home courtyards — and each one changes how the tying schedule is planned. A hotel booking usually means a fixed preparation room and predictable access, while a home or courtyard function often needs the team to adapt around family rituals happening in parallel. We ask about the venue type early so the right number of artists and the right pace are set from the start, rather than guessing on the day. Peak wedding months in and around English River bring tighter artist availability, so dates during the busiest weeks benefit from earlier confirmation. Off-season and weekday bookings tend to have more flexibility on timing and can sometimes accommodate later confirmations. Either way, the core planning stays the same: confirm the property, the room being used for styling, and roughly how many people need to be ready before the first ritual or the baraat departure. Weather is a smaller factor for most English River bookings since safa tying happens indoors or under cover, but for any outdoor portrait session immediately after styling, we factor in extra time so fabric and finishing hold up under natural light.",
    "For English River weddings, the package decision is really a headcount decision first and a style decision second. Once we know how many people need styling — the groom, close family, and the wider baraat if applicable — we can recommend artist numbers and a realistic tying window. Families sometimes assume a bigger package is always safer, but an accurately sized package based on your actual guest list is usually more cost-effective and easier to schedule than an oversized one. If you're unsure of the final numbers this early, a rough range is enough to start the conversation; we'll confirm the exact count closer to the date. Multi-function weddings in English River — where the same family books a haldi, sangeet and wedding day styling — often benefit from a combined package rather than three separate bookings, since it keeps pricing and artist scheduling consistent across all three events. If your celebration includes destination elements, such as a portion of the wedding happening outside English River itself, mention that upfront too, since it changes how the package and travel logistics are structured.",
  ],
  "saint-louis": [
    "Across Saint Louis, wedding venues range from compact family halls to larger destination-style properties, and the safa tying plan changes with the scale of the venue. Smaller, more intimate functions usually need a shorter, tighter schedule with the groom styled first and the rest of the group following quickly after. Larger multi-hall or multi-day venues need a longer plan, sometimes spanning more than one function in the same property, and we treat each function as its own booking within the same visit. Local venues in Saint Louis are generally easy to access, which keeps setup time short, but properties further from the main area may need an earlier arrival buffer. We recommend sharing the venue name and rough guest count as early as possible, even before the date is fully locked, so we can flag any availability concerns during peak wedding weeks. If the celebration includes more than one ceremony — a haldi, a sangeet, the main wedding — let us know all the dates together so the Saint Louis team can plan artist availability across the full run rather than one date at a time.",
    "For Saint Louis weddings, the package decision is really a headcount decision first and a style decision second. Once we know how many people need styling — the groom, close family, and the wider baraat if applicable — we can recommend artist numbers and a realistic tying window. Families sometimes assume a bigger package is always safer, but an accurately sized package based on your actual guest list is usually more cost-effective and easier to schedule than an oversized one. If you're unsure of the final numbers this early, a rough range is enough to start the conversation; we'll confirm the exact count closer to the date. Multi-function weddings in Saint Louis — where the same family books a haldi, sangeet and wedding day styling — often benefit from a combined package rather than three separate bookings, since it keeps pricing and artist scheduling consistent across all three events. If your celebration includes destination elements, such as a portion of the wedding happening outside Saint Louis itself, mention that upfront too, since it changes how the package and travel logistics are structured.",
  ],
  "roche-caiman": [
    "Across Roche Caiman, wedding venues range from compact family halls to larger destination-style properties, and the safa tying plan changes with the scale of the venue. Smaller, more intimate functions usually need a shorter, tighter schedule with the groom styled first and the rest of the group following quickly after. Larger multi-hall or multi-day venues need a longer plan, sometimes spanning more than one function in the same property, and we treat each function as its own booking within the same visit. Local venues in Roche Caiman are generally easy to access, which keeps setup time short, but properties further from the main area may need an earlier arrival buffer. We recommend sharing the venue name and rough guest count as early as possible, even before the date is fully locked, so we can flag any availability concerns during peak wedding weeks. If the celebration includes more than one ceremony — a haldi, a sangeet, the main wedding — let us know all the dates together so the Roche Caiman team can plan artist availability across the full run rather than one date at a time.",
    "For Roche Caiman weddings, the package decision is really a headcount decision first and a style decision second. Once we know how many people need styling — the groom, close family, and the wider baraat if applicable — we can recommend artist numbers and a realistic tying window. Families sometimes assume a bigger package is always safer, but an accurately sized package based on your actual guest list is usually more cost-effective and easier to schedule than an oversized one. If you're unsure of the final numbers this early, a rough range is enough to start the conversation; we'll confirm the exact count closer to the date. Multi-function weddings in Roche Caiman — where the same family books a haldi, sangeet and wedding day styling — often benefit from a combined package rather than three separate bookings, since it keeps pricing and artist scheduling consistent across all three events. If your celebration includes destination elements, such as a portion of the wedding happening outside Roche Caiman itself, mention that upfront too, since it changes how the package and travel logistics are structured.",
  ],
  "beau-vallon": [
    "Beau Vallon weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around Beau Vallon often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so Beau Vallon dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the Beau Vallon booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "For a travelling Beau Vallon booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Beau Vallon trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Beau Vallon bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "anse-royale": [
    "Because Anse Royale sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Anse Royale are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Anse Royale bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Anse Royale celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "For a travelling Anse Royale booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Anse Royale trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Anse Royale bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "anse-boileau": [
    "Anse Boileau weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around Anse Boileau often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so Anse Boileau dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the Anse Boileau booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "For a travelling Anse Boileau booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Anse Boileau trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Anse Boileau bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "grand-anse": [
    "Grand Anse weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around Grand Anse often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so Grand Anse dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the Grand Anse booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "Choosing a package for an Grand Anse wedding starts with the same questions as any booking — how many people, what level of detail for the groom, and whether the wider baraat needs full styling or a simpler coordinated look — but travel from Seychelles adds planning time worth building in. Because the team commits to a specific date and route for a Grand Anse assignment, package and quantity decisions are best finalised a week or two earlier than they would be for a local wedding, giving enough time to prepare fabric and confirm the final artist count. If your Grand Anse celebration includes multiple functions across a short trip, a combined package covering all of them is usually more practical than booking each date separately. We're glad to talk through a realistic package once we know your approximate headcount, the venue type, and whether the wedding is a single day or a multi-day stay — share what you have so far and we'll take it from there.",
  ],
  "glacis": [
    "Because Glacis sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Glacis are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Glacis bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Glacis celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "For a travelling Glacis booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Glacis trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Glacis bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "bel-ombre": [
    "Bel Ombre weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around Bel Ombre often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so Bel Ombre dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the Bel Ombre booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "Choosing a package for an Bel Ombre wedding starts with the same questions as any booking — how many people, what level of detail for the groom, and whether the wider baraat needs full styling or a simpler coordinated look — but travel from Seychelles adds planning time worth building in. Because the team commits to a specific date and route for a Bel Ombre assignment, package and quantity decisions are best finalised a week or two earlier than they would be for a local wedding, giving enough time to prepare fabric and confirm the final artist count. If your Bel Ombre celebration includes multiple functions across a short trip, a combined package covering all of them is usually more practical than booking each date separately. We're glad to talk through a realistic package once we know your approximate headcount, the venue type, and whether the wedding is a single day or a multi-day stay — share what you have so far and we'll take it from there.",
  ],
  "takamaka": [
    "Because Takamaka sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Takamaka are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Takamaka bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Takamaka celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "For a travelling Takamaka booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Takamaka trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Takamaka bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "baie-lazare": [
    "Because Baie Lazare sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Baie Lazare are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Baie Lazare bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Baie Lazare celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "Choosing a package for an Baie Lazare wedding starts with the same questions as any booking — how many people, what level of detail for the groom, and whether the wider baraat needs full styling or a simpler coordinated look — but travel from Seychelles adds planning time worth building in. Because the team commits to a specific date and route for a Baie Lazare assignment, package and quantity decisions are best finalised a week or two earlier than they would be for a local wedding, giving enough time to prepare fabric and confirm the final artist count. If your Baie Lazare celebration includes multiple functions across a short trip, a combined package covering all of them is usually more practical than booking each date separately. We're glad to talk through a realistic package once we know your approximate headcount, the venue type, and whether the wedding is a single day or a multi-day stay — share what you have so far and we'll take it from there.",
  ],
  "port-glaud": [
    "Port Glaud weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around Port Glaud often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so Port Glaud dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the Port Glaud booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "Choosing a package for an Port Glaud wedding starts with the same questions as any booking — how many people, what level of detail for the groom, and whether the wider baraat needs full styling or a simpler coordinated look — but travel from Seychelles adds planning time worth building in. Because the team commits to a specific date and route for a Port Glaud assignment, package and quantity decisions are best finalised a week or two earlier than they would be for a local wedding, giving enough time to prepare fabric and confirm the final artist count. If your Port Glaud celebration includes multiple functions across a short trip, a combined package covering all of them is usually more practical than booking each date separately. We're glad to talk through a realistic package once we know your approximate headcount, the venue type, and whether the wedding is a single day or a multi-day stay — share what you have so far and we'll take it from there.",
  ],
  "baie-sainte-anne": [
    "Because Baie Sainte Anne sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Baie Sainte Anne are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Baie Sainte Anne bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Baie Sainte Anne celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "Choosing a package for an Baie Sainte Anne wedding starts with the same questions as any booking — how many people, what level of detail for the groom, and whether the wider baraat needs full styling or a simpler coordinated look — but travel from Seychelles adds planning time worth building in. Because the team commits to a specific date and route for a Baie Sainte Anne assignment, package and quantity decisions are best finalised a week or two earlier than they would be for a local wedding, giving enough time to prepare fabric and confirm the final artist count. If your Baie Sainte Anne celebration includes multiple functions across a short trip, a combined package covering all of them is usually more practical than booking each date separately. We're glad to talk through a realistic package once we know your approximate headcount, the venue type, and whether the wedding is a single day or a multi-day stay — share what you have so far and we'll take it from there.",
  ],
  "anse-volbert": [
    "Because Anse Volbert sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Anse Volbert are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Anse Volbert bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Anse Volbert celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "For a travelling Anse Volbert booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Anse Volbert trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Anse Volbert bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "grand-anse-praslin": [
    "Because Grand Anse Praslin sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around Grand Anse Praslin are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects Grand Anse Praslin bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the Grand Anse Praslin celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "For a travelling Grand Anse Praslin booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Grand Anse Praslin trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Grand Anse Praslin bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "la-passe": [
    "Because La Passe sits outside the immediate Seychelles service area, we treat every booking there as a planned trip rather than an on-call visit, which means venue and timing details are confirmed further in advance than a local Seychelles wedding would need. Hotel and resort venues around La Passe are generally the easiest to plan around, since they tend to have a dedicated preparation room and predictable access for the team. Home functions or less conventional venues can still be accommodated, but we ask for more detail on the space itself — where the family will be getting ready, and roughly how much room is available. Wedding season timing affects La Passe bookings just as it does Seychelles itself, so peak-month dates are worth confirming early to avoid a scheduling clash with other travelling assignments. If the La Passe celebration spans more than a single day, let us know the full schedule upfront so travel and accommodation for the artists, where relevant, can be planned as part of the same booking rather than arranged separately.",
    "Choosing a package for an La Passe wedding starts with the same questions as any booking — how many people, what level of detail for the groom, and whether the wider baraat needs full styling or a simpler coordinated look — but travel from Seychelles adds planning time worth building in. Because the team commits to a specific date and route for a La Passe assignment, package and quantity decisions are best finalised a week or two earlier than they would be for a local wedding, giving enough time to prepare fabric and confirm the final artist count. If your La Passe celebration includes multiple functions across a short trip, a combined package covering all of them is usually more practical than booking each date separately. We're glad to talk through a realistic package once we know your approximate headcount, the venue type, and whether the wedding is a single day or a multi-day stay — share what you have so far and we'll take it from there.",
  ],
  "la-reunion": [
    "La Reunion weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around La Reunion often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so La Reunion dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the La Reunion booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "For a travelling La Reunion booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function La Reunion trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because La Reunion bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
  "anse-source-d-argent": [
    "Anse Source d'Argent weddings booked from our Seychelles base are usually planned as a single travelling assignment rather than a standard local visit, so venue and season details matter more than they would for an in-town booking. Resort and destination-style venues around Anse Source d'Argent often have their own preparation spaces, which we confirm with the property directly where possible, and lawn or outdoor venues need a weather-aware backup plan for the styling area. Peak wedding season brings more competing bookings across the wider Seychelles region, so Anse Source d'Argent dates during busy weeks should be confirmed with more lead time than an off-season date would need. Because the team is travelling specifically for the Anse Source d'Argent booking, we also factor in road or transfer time when planning the arrival buffer — an earlier ceremony time generally means an earlier departure from Seychelles. If the venue is unfamiliar to us, sharing photos or a location pin in advance helps us plan the right team size and equipment before the day itself, rather than adjusting on arrival.",
    "For a travelling Anse Source d'Argent booking, the right package depends on guest count just as it would locally, but travel adds one more variable worth planning around: how many functions the team needs to cover during the trip. A single-ceremony booking is the most straightforward — one date, one venue, one styling window. A multi-function Anse Source d'Argent trip, covering a haldi or sangeet alongside the main wedding, is usually more efficient as one combined package rather than separate bookings, since the team is already travelling from Seychelles and can plan artist time across the full stay. Fabric and accessory choices work the same way they would for a local booking — a coordinated palette for the groom and family, reviewed against outfit references before the team departs. Because Anse Source d'Argent bookings involve travel, we recommend finalising the package a little earlier than you might for an in-town wedding, so fabric, artist numbers and the travel schedule can all be confirmed together rather than adjusted at short notice.",
  ],
};


const serviceProfiles: Record<string, [string, string, string]> = {
  "wedding-safa-tying": [
    "Professional wedding safa tying combines fabric planning, artist scheduling and on-location execution. We separate the groom's detailed appointment from family and baraati batches so the final group looks coordinated without delaying the procession.",
    "Rajasthani, Rajwadi, Jodhpuri, Marwari and Bandhani safa styles create different height, volume and colour effects. The best wedding safa is selected from the outfit, face profile, event setting and time the groom will wear it.",
    "Wedding safa price depends on fabric, quantity, fold, accessories, travel and artist count. Share the event date, venue, ready-by time and separate groom, family and guest quantities for a useful package recommendation.",
  ],
  "groom-pagdi": [
    "Groom pagdi styling in Seychelles starts with the outfit and jewellery, working backward to a fold and colour that photograph well against that specific sherwani.",
    "A kalgi, brooch or pearl chain is added last, and only if it strengthens the overall look rather than competing with the fabric detailing.",
    "Booking after the main outfit is chosen gives the most accurate styling plan — trying to fix the pagdi profile before the sherwani is settled usually means redoing the choice later.",
  ],
  "baraati-safa": [
    "A baraati safa service is designed for speed, consistency and a strong group identity. Guests are divided into batches and each artist follows one agreed fold so the procession photographs feel coordinated from front to back.",
    "Bandhani, maroon, saffron, pink and mustard wedding-party safas create visible colour in a moving baraat. Parents and brothers can use a complementary shade or border while the wider guest group stays uniform.",
    "Baraati safa packages are calculated from guest quantity and the time available before departure. Keep a small fabric buffer for late additions and appoint one coordinator to keep the next group ready for tying.",
  ],
  "destination-wedding-safa": [
    "Destination weddings near Seychelles usually involve more than one function, so the safa team plans a schedule across rooms and days rather than a single tying slot.",
    "Lighter, travel-friendly fabrics in ivory, rust and muted gold tones tend to photograph well in both outdoor destination light and hotel interiors.",
    "The most useful destination quote request includes the property name, route, reporting time and a per-function guest count — not just the wedding date.",
  ],
  "family-pagdi": [
    "In Seychelles, family pagdi bookings work best when the groom's look is agreed first, since every relative's style is planned to complement rather than match it exactly.",
    "Two linked colour groups — one per side of the family — keep both families visually distinct while still reading as one coordinated wedding party.",
    "Mentioning elders' comfort needs and children's approximate ages in advance lets the artist plan fit and tension correctly for each person.",
  ],
  "custom-safa-colours": [
    "Custom colour planning in Seychelles starts from your existing references — outfits, florals or décor boards — rather than a fixed swatch book.",
    "Traditional maroon and red suit classical ceremonies, while sage, blush and muted gold support a softer, more contemporary wedding palette; the groom can still take a controlled contrast within the same direction.",
    "Colours are best locked in once the principal outfits are finalised, and a physical fabric sample is worth checking since screen colours rarely match exactly.",
  ],
};

function hashIndex(key: string, mod: number): number {
  let h = 0;
  for (let i = 0; i < key.length; i++) {
    h = (h * 31 + key.charCodeAt(i)) >>> 0;
  }
  return h % mod;
}

const LOCATION_HEADING_TEMPLATES: ((n: string) => string)[] = [
  (n) => `Wedding safa planning for ${n}`,
  (n) => `A wedding safa wala's guide to ${n}`,
  (n) => `Booking wedding safa tying in ${n}`,
  (n) => `Groom pagdi and safa tying, planned for ${n}`,
  (n) => `${n}: your wedding safa booking guide`,
];

const LOCATION_INTRO_TEMPLATES: ((n: string) => string)[] = [
  (n) => `This ${n} guide combines local preparation needs with high-intent wedding safa, groom pagdi and baraati safa searches from our keyword research.`,
  (n) => `Families searching for a wedding safa wala in ${n} usually ask the same handful of questions — this guide answers them together.`,
  (n) => `Before booking wedding safa tying in ${n}, it helps to know what a local safa wala actually needs from you to plan the day well.`,
  (n) => `${n} weddings each have their own venue and guest pattern, so this guide covers what a wedding safa wala in ${n} plans around.`,
  (n) => `A short, practical guide to groom pagdi styling and wedding safa tying for couples planning a celebration in ${n}.`,
];

const LOCATION_BLOCK_TITLE_SETS: ((n: string) => [string, string, string])[] = [
  (n) => [`Wedding safa service in ${n}`, `Groom pagdi styles for ${n}`, `Booking and safa packages in ${n}`],
  (n) => [`How wedding safa tying works in ${n}`, `Colour and fabric choices in ${n}`, `What to share when booking in ${n}`],
  (n) => [`Safa wala service for ${n} weddings`, `Groom pagdi options in ${n}`, `Planning your ${n} safa booking`],
  (n) => [`On-location safa tying in ${n}`, `Styling the groom pagdi for ${n}`, `${n} booking checklist`],
];


const serviceExtraBlocks: Record<string, [string, string][]> = {
  "wedding-safa-tying": [
    ["What happens on the day in Seychelles", "A typical Seychelles booking starts with the artists confirming the preparation room and laying out the agreed fabric before anyone sits down. The groom's session comes first and is treated with the most care — this is the look that appears in the most photographs, so kalgi, brooch or pearl placement is checked carefully against the sherwani and any headwear jewellery. Once that's done, the team moves to family members, working through a coordinated but faster fold, before finishing with the wider baraat as one organised batch. If the guest list is large, additional artists are brought in so the pace stays realistic rather than rushed. We also keep a small quantity buffer in reserve, since late fitting adjustments or an extra guest are common on the day. The goal throughout is a schedule that protects the ceremony start time — the groom is portrait-ready well before the main event, and the baraat is fully styled before the procession is due to leave."],
    ["Planning your Seychelles booking properly", "The smoothest Seychelles bookings are the ones where we have the full picture early: date, venue, approximate guest count, and any outfit or décor references you already have. Even a rough estimate on numbers is enough to start — we'll help refine it as the date gets closer. Because pricing depends on fabric, quantity and styling complexity together, sharing these details in one message tends to get you a more accurate quote than asking for a starting price alone. If your celebration in Seychelles spans multiple days or functions, let us know the full schedule rather than just the main wedding date, since a combined booking is usually easier for us to plan artist time around. We recommend finalising your safa colour and fabric direction a couple of weeks before the event, particularly if your date falls during a busy wedding season in Seychelles, so there's enough time to prepare and no last-minute compromises on the details that matter most in photographs."],
  ],
  "groom-pagdi": [
    ["The groom's styling session in Seychelles", "For a Seychelles groom pagdi booking, the session is scheduled to sit right between the sherwani being finished and the first formal photographs of the day. The artist works with the groom directly, checking fold, height and balance against his face and the outfit before finishing with any chosen accessory — kalgi, brooch, feather or pearl detailing, positioned and adjusted until it photographs cleanly from multiple angles. This is intentionally the most unhurried part of the whole booking, since the groom's look carries the most visual weight across the day's photographs. Once it's finished, we take a moment to review it against the sherwani and jewellery one more time before moving on to the rest of the wedding party. If a specific reference style has been shared in advance, the artist works from that directly rather than defaulting to a generic profile, which keeps the final result closer to what the groom actually pictured."],
    ["Booking groom pagdi styling in Seychelles", "When booking groom pagdi styling in Seychelles, the most useful thing to share upfront is a reference — a photo, a Pinterest board, or even just a description of the silhouette the groom prefers. From there we can recommend a fabric and colour direction that works with the sherwani and jewellery already chosen. If the groom wants to compare more than one profile before deciding, mention that early, since a trial or a more detailed consultation is easiest to arrange when there's still time before the wedding date. We'd also recommend confirming the exact time the groom needs to be ready by — not just the ceremony time — since this is what determines how early the session needs to start. For Seychelles bookings during peak wedding season, an earlier confirmation gives more room to finalise colour and accessory choices without last-minute compromises."],
  ],
  "baraati-safa": [
    ["Managing a large baraat in Seychelles", "For a large baraati group in Seychelles, the team works in organised batches rather than styling everyone one at a time from a single queue. One repeatable fold and colour direction is agreed in advance, which lets multiple artists work in parallel once the group size calls for it, keeping the overall pace realistic even for sizeable guest lists. A coordinator usually manages the flow — directing guests to the tying area in a sensible order, and keeping a small buffer of fabric and time available for anyone who arrives later than expected. Because the baraat's safas are meant to photograph as one coordinated group, we keep the fold and colour consistent across everyone rather than allowing small variations to creep in guest by guest. Close family can still be given a subtly different or more detailed treatment within the same overall palette, so they remain visually connected to the group while standing slightly apart from the general baraat."],
    ["Booking baraati safa styling in Seychelles", "Booking baraati safa styling for a Seychelles wedding starts with an accurate headcount — even an estimate is useful, since it determines how many artists we bring and how the schedule is structured. If the number is likely to change closer to the date, let us know that upfront so we can plan with some flexibility built in. We'd also recommend deciding early whether close family should have a slightly more detailed look than the wider baraat, since this affects both fabric planning and the tying sequence on the day. For larger Seychelles celebrations, confirming the booking a few weeks ahead gives us time to schedule enough artists, particularly during busy wedding months when availability is tighter across the board."],
  ],
  "destination-wedding-safa": [
    ["How a destination assignment runs", "A destination assignment starts well before the wedding day itself — fabric, accessories and the full colour direction are confirmed and packed in advance, since there's no opportunity to make last-minute changes once the team has travelled. On arrival, the artists confirm the preparation room with the venue or hotel directly, then work through the same sequence as a local booking: groom first, in an unhurried session, followed by close family and the wider baraat in coordinated batches. For multi-day destination weddings, each function is treated as its own styling session within the same trip, so a haldi, sangeet and the main wedding day are all planned as part of one continuous schedule rather than separate bookings. Because travel time and property access can vary significantly between venues, we build in an arrival buffer that accounts for the specific location, so the team is on-site and ready well before the first styling session is due to begin."],
    ["Booking a destination safa team for Seychelles", "The most useful destination quote request includes the property, the route from our base, the full multi-day schedule if there is one, and an approximate guest count for each function. This gives us what we need to plan travel, a realistic arrival buffer, and artist accommodation if the assignment requires an overnight stay. If your celebration spans more than one day, share every date together rather than requesting quotes function by function — a combined destination package is usually more efficient to plan and price than treating each day separately. Because destination bookings involve travel commitments on our side, we'd suggest confirming these further in advance than a local wedding, especially if your dates fall during a busy travel season."],
  ],
  "family-pagdi": [
    ["Styling the wider family in Seychelles", "Once the groom's pagdi is complete, family styling in Seychelles begins at a faster, more streamlined pace, though still following a coordinated fold and palette. Close relatives — fathers, brothers, and other immediate family — are often given a slightly more detailed look than the wider group, using a refined fold or a small accessory that sets them subtly apart without competing with the groom. For families choosing two separate colour palettes, one per side, the artist keeps the groups organised so there's no mix-up on the day. We treat comfort as a real consideration here, particularly for older relatives — a softer tension and gentler finish are used whenever comfort is flagged in advance. Children are usually styled toward the end of the family session, since their turbans are simpler and quicker to complete than an adult's more detailed fold."],
    ["Booking family pagdi styling in Seychelles", "Booking family pagdi styling in Seychelles works best when you can tell us roughly how many family members need to be styled, and whether both sides of the family want the same palette or two distinct but complementary colours. If any elders have specific comfort needs, mentioning this in advance lets the artist adjust fit and tension accordingly rather than working it out on the day. For families including children, a rough headcount and approximate ages helps us plan time realistically, since younger children's sessions are usually shorter. We'd also suggest deciding early whether close family — parents and siblings — should have a more detailed look than everyone else, since this shapes both the fabric plan and the tying order once the day arrives."],
  ],
  "custom-safa-colours": [
    ["Reviewing colours before the Seychelles event", "By the time we're on-site for a Seychelles booking, the colour direction has already been settled — the day itself is about making sure that choice translates properly into the finished look. The artist checks the fabric against the groom's outfit one more time before styling begins, adjusting the fold where needed so the colour reads clearly in both daylight and any indoor lighting the venue has. For weddings using more than one coordinated shade across family and baraat, we keep a clear system for which colour is assigned to which group, so the finished result looks intentional rather than mismatched. If lighting conditions at the Seychelles venue are unusual — very warm indoor light, or strong outdoor glare — small adjustments are made on the spot to keep the colour looking true rather than distorted in photographs."],
    ["Planning your custom colour direction in Seychelles", "For a Seychelles custom colour booking, the fastest route to a good recommendation is sharing what's already fixed — the sherwani, the bride's outfit, or a décor moodboard — since the safa colour is chosen to complement rather than compete with those choices. A physical fabric swatch or a clear reference photo works better than a colour name alone, since shades can read very differently in person. We'd recommend finalising your direction early enough to check the fabric in more than one lighting condition, ideally both daylight and the venue's indoor lighting, so there are no surprises on the day. If you're planning multiple coordinated shades — one for the groom, another for family or baraat — settling this ahead of time also makes it easier for us to plan fabric quantities accurately."],
  ],
};

function makeContent(pageName: string, profile: [string, string, string], isLocation: boolean): PageSeoContent {
  if (isLocation) {
    const heading = LOCATION_HEADING_TEMPLATES[hashIndex(`heading|${pageName}`, LOCATION_HEADING_TEMPLATES.length)](pageName);
    const introduction = LOCATION_INTRO_TEMPLATES[hashIndex(`intro|${pageName}`, LOCATION_INTRO_TEMPLATES.length)](pageName);
    const [t1, t2, t3] = LOCATION_BLOCK_TITLE_SETS[hashIndex(`blocks|${pageName}`, LOCATION_BLOCK_TITLE_SETS.length)](pageName);
    const extra = locationExtraBlocks[pageName.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")];
    return {
      heading,
      introduction,
      blocks: [
        { title: t1, body: profile[0] },
        { title: t2, body: profile[1] },
        { title: t3, body: profile[2] },
        ...(extra ? [
          { title: `Venues and season notes for ${pageName}`, body: extra[0] },
          { title: `Choosing the right safa package in ${pageName}`, body: extra[1] },
        ] : []),
      ],
    };
  }
  return {
    heading: `${pageName}: styles, packages and booking guidance`,
    introduction: `A practical guide built around the service terms couples and families use when comparing professional safa tying in Seychelles.`,
    blocks: [
      { title: "What the service includes", body: profile[0] },
      { title: "Styles, colours and finishing", body: profile[1] },
      { title: "Price, packages and booking", body: profile[2] },
    ],
  };
}

export function getLocationSeoContent(slug: string, name: string): PageSeoContent {
  const profile = locationProfiles[slug];
  if (!profile) throw new Error(`Missing SEO content profile for location: ${slug}`);
  return makeContent(name, profile, true);
}

export function getServiceSeoContent(slug: string, name: string): PageSeoContent {
  const profile = serviceProfiles[slug];
  if (!profile) throw new Error(`Missing SEO content profile for service: ${slug}`);
  const base = makeContent(name, profile, false);
  const extra = serviceExtraBlocks[slug];
  if (!extra) return base;
  return { ...base, blocks: [...base.blocks, ...extra.map(([title, body]) => ({ title, body }))] };
}
